spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1

        ## Service3
        - id: python-service
          uri: lb://python-service
          predicates:
            - Path=/python-service/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
