spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/jwt_security
    username: postgres
    password: 433UQM!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
